import { useRef } from "react";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import ScrollToTop from "@/components/ScrollToTop";

export default function Home() {
  const Video = useRef(null);
  const About = useRef(null);
  const Features = useRef(null);
  const PersuasiveFeatures = useRef(null);
  const Description = useRef(null);
  const Links = useRef(null);
  const Contact = useRef(null);

  const scrollToSection = (section) => {
    let elementRef;
    switch (section) {
      case "Video":
        elementRef = Video;
        break;
      case "About":
        elementRef = About;
        break;
      case "Features":
        elementRef = Features;
        break;
      case "PersuasiveFeatures":
        elementRef = PersuasiveFeatures;
        break;
      case "Description":
        elementRef = Description;
        break;
      case "Links":
        elementRef = Links;
        break;
      case "Contact":
        elementRef = Contact;
        break;
      default:
        break;
    }

    if (elementRef && elementRef.current) {
      window.scrollTo({
        top: elementRef.current.offsetTop,
        behavior: "instant",
      });
    }
  };

  const scrollToHeader = () => {
    if (headerRef && headerRef.current) {
      window.scrollTo({
        top: headerRef.current.offsetTop,
        behavior: "smooth",
      });
    }
  };

  const scrollToTop = () => {
    window.scrollTo({
      top: 0,
      behavior: "smooth",
    });
  };

  return (
    <>
      <Head>
        <title>Local Harvest Marketing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fork-awesome@1.2.0/css/fork-awesome.min.css" integrity="sha256-XoaMnoYC5TH6/+ihMEnospgm0J1PM/nioxbOUdnM8HY=" crossorigin="anonymous"></link>
      </Head>
      <main className={`${styles.main}`}>
        <Header scrollToSection={scrollToSection} scrollToTop={scrollToTop} />
        <ScrollToTop/>
        <div className={styles.LandingArea}>

        </div>
        <div ref={Video} className={`${styles.area} ${styles.areaVideo}`}>
          <h3>Video</h3>
        </div>
        <div ref={About} className={`${styles.area} ${styles.areaAbout}`}>
          <h3>About</h3>
        </div>
        <div ref={Features} className={`${styles.area} ${styles.areaFeatures}`}>
          <h3>Features</h3>
        </div>
        <div ref={PersuasiveFeatures} className={`${styles.area} ${styles.areaPersuasiveFeatures}`}>
          <h3>Persuasive Features</h3>
        </div>
        <div ref={Description} className={`${styles.area} ${styles.areaDescription}`}>
          <h3>Description</h3>
        </div>
        <div ref={Links} className={`${styles.area} ${styles.areaLinks}`}>
          <h3>Links</h3>
        </div>
        <div ref={Contact} className={`${styles.area} ${styles.areaContact}`}>
          <h3>Contact</h3>
        </div>
      </main>
    </>
  );
}
